### ISSUE TITLE
Support Tailwind v3.x

### ISSUE THREAD

**Issue by pvinis** [vadimdemedes/tailwind-rn#116] opened 2021-12-30 04:13 UTC
what is needed for that?

**Comment by MaganAnkur** [comment] 2022-01-05 22:30
@pvinis npx create-tailwind-rn not generating CSS with tailwind v3

**Comment by vadimdemedes** [comment] 2022-01-05 22:32
I'm currently working on a major new release to support latest Tailwind in `v4` branch.

**Comment by vadimdemedes** [comment] 2022-01-05 22:36
Duplicate of https://github.com/vadimdemedes/tailwind-rn/issues/71.

**Closed by vadimdemedes** 2022-01-05 22:36 UTC
